// Generated with Shader Minifier 1.5.1 (https://github.com/laurentlb/Shader_Minifier/)
#ifndef FRAG_DRAW_H_
# define FRAG_DRAW_H_
# define VAR_fragColor "v"
# define VAR_frame "y"
# define VAR_resolution "m"

const char *draw_frag =
 "#version 430\n"
 "layout(location=0)out vec4 v;"
 "layout(location=0)uniform vec4 m;"
 "layout(location=1)uniform int y;"
 "const float f=2*acos(-1);"
 "vec3 s(vec3 v)"
 "{"
   "uvec3 y=floatBitsToUint(v);"
   "y=(y>>16u^y.yzx)*1111111111u;"
   "y=(y>>16u^y.yzx)*1111111111u;"
   "y=(y>>16u^y.yzx)*1111111111u;"
   "return vec3(y)/float(-1u);"
 "}"
 "vec2 s(float v)"
 "{"
   "return vec2(cos(v),sin(v));"
 "}"
 "mat2 n(float v)"
 "{"
   "return mat2(cos(v),sin(v),-sin(v),cos(v));"
 "}"
 "mat3 n(vec3 v)"
 "{"
   "v=normalize(v);"
   "vec3 y=normalize(cross(abs(v.y)<.99?"
     "vec3(0,1,0):"
     "vec3(0,0,1),v));"
   "return mat3(y,cross(v,y),v);"
 "}"
 "vec3 p(vec3 v)"
 "{"
   "vec3 m=vec3(0);"
   "for(int i=0;i++<5;)"
     "v*=2.*n(vec3(3,4,-5)),v+=sin(v.yzx),m=m*2.+cross(cos(v),sin(v.zxy));"
   "return m/31.;"
 "}"
 "vec3 n(vec2 v,vec2 y,float x)"
 "{"
   "y=abs(v)-y;"
   "float z=max(y.x,y.y);"
   "if(z>0.)"
     "{"
       "vec2 z=max(y,0.);"
       "float f=length(z);"
       "return vec3(sign(v)*z/f,f-x);"
     "}"
   "return vec3(sign(v)*step(vec2(z),y),z-x);"
 "}"
 "void n(vec2 v,inout float f,float m,float y,float x,float z,float n)"
 "{"
   "n=n==0.?"
     ".001:"
     "n;"
   "v-=vec2(m,y);"
   "vec2 a=vec2(x-m,z-y),p=s(abs(n)/2.);"
   "m=length(a);"
   "y=m/2./p.y;"
   "v*=mat2(a.y,-a.x,a.x,a.y)/m;"
   "v.x*=sign(n);"
   "v-=y*p*vec2(-1,1);"
   "v.y=abs(v.y);"
   "f=min(f,p.y*v.x>p.x*v.y?"
     "abs(length(v)-y):"
     "length(v-p*y));"
 "}"
 "void n(inout vec4 v,vec3 y,vec3 x,vec3 m)"
 "{"
   "y=-y/x;"
   "m=abs(m/x);"
   "y-=m;"
   "m+=y+m;"
   "float z=max(max(y.x,y.y),y.z),w=min(min(m.x,m.y),m.z);"
   "if(w>=z)"
     "{"
       "if(z>0.&&z<v.w)"
         "v=vec4(-sign(x)*step(vec3(z),y),z);"
       "if(w>0.&&w<v.w)"
         "v=vec4(-sign(x)*step(m,vec3(w)),w);"
     "}"
 "}"
 "void n(inout vec4 v,vec3 y,vec3 x,float z)"
 "{"
   "float m=dot(y,x);"
   "z=m*m-dot(y,y)+z*z;"
   "if(z>0.)"
     "{"
       "z=sqrt(z);"
       "float f=-m-z;"
       "if(f>0.&&f<v.w)"
         "v=vec4(normalize(y+x*f),f);"
       "f=-m+z;"
       "if(f>0.&&f<v.w)"
         "v=vec4(-normalize(y+x*f),f);"
     "}"
 "}"
 "void n(inout vec4 v,vec3 y,vec3 x,vec3 z,float m)"
 "{"
   "float f=dot(z,z),p=dot(z,x),s=dot(y,z),w=f-p*p,a=f*dot(y,x)-s*p,l=a*a-w*(f*dot(y,y)-s*s-m*m*f);"
   "if(l>0.)"
     "{"
       "float d=(-a-sqrt(l))/w;"
       "if(d>0.)"
         "{"
           "float a=clamp(s+d*p,0.,f);"
           "if(a>0.&&a<f&&d<v.w)"
             "v=vec4((y+x*d-a/f*z)/m,d);"
           "n(v,y-clamp(a,0.,f)/f*z,x,m);"
         "}"
     "}"
 "}"
 "float n(float v,float y)"
 "{"
   "float z=max(1.5-abs(v-y),0.)/1.5;"
   "return min(v,y)-z*z*z*1.5/6.;"
 "}"
 "float t(vec3 v)"
 "{"
   "return.8*n(n(length(v+.4*p(v*.5+14.)-vec3(0,1.2,0))-.8,2.5-v.y),length(vec2(v.x-clamp(v.x,-1.5,1.5),v.y)))+.01;"
 "}"
 "void main()"
 "{"
   "v*=0.;"
   "vec2 z=gl_FragCoord.xy/m.xy-.5;"
   "z.x*=m.x/m.y;"
   "if(abs(z.x)<.7)"
     "{"
       "vec3 x=s(vec3(z,y));"
       "for(int i=0;i++<10;)"
         "{"
           "vec2 y=z*n(.01)+x.xy/m.y;"
           "x=s(x);"
           "vec3 a=vec3(-.1,1.6,11),w=normalize(vec3(y,-4));"
           "w.zx*=n(.01);"
           "w.yz*=n(.045);"
           "w=a+w*10.;"
           "a+=.01*vec3(s(f*x.z)*sqrt(x.y),0);"
           "w=normalize(w-a);"
           "vec3 l=vec3(1.2-length(z)*length(z));"
           "for(int i=0;i++<5;)"
             "{"
               "mat3 m;"
               "vec4 y=vec4(100),z=vec4(100);"
               "n(z,a-vec3(0,2.35,-2),w,vec3(.15,.15,.05));"
               "if(z.w<y.w)"
                 "y=z,m=mat3(vec3(a+w*y.w-vec3(0,2.35,-2)),vec3(0),vec3(5));"
               "a.zx*=n(.2);"
               "w.zx*=n(.2);"
               "a-=vec3(0,.4,0);"
               "z=vec4(100);"
               "n(z,a,w,vec3(.45,.3,0));"
               "if(z.w<y.w)"
                 "{"
                   "vec3 v=a+w*z.w;"
                   "float x=max(n(v.xy,vec2(.45,.3),0.).z,-n(abs(abs(v.xy-vec2(0,.28))-vec2(.3,0)),vec2(.015,0),.005).z)+.01*p(8.*v).x;"
                   "if(x<0.)"
                     "y=z,m=mat3(vec3(v),vec3(x),vec3(6)),y.zx*=n(-.2);"
                 "}"
               "a+=vec3(0,.4,0);"
               "z=vec4(100);"
               "n(z,a-vec3(-.6,.75,0),w,vec3(0,-1,.3),.02);"
               "n(z,a-vec3(-.6,.75,0),w,vec3(0,-1,-.3),.02);"
               "n(z,a-vec3(-.6,.75,0),w,vec3(1.2,0,0),.02);"
               "n(z,a-vec3(-.6,.1,.19),w,vec3(1.2,0,0),.01);"
               "n(z,a-vec3(-.6,.1,-.19),w,vec3(1.2,0,0),.01);"
               "n(z,a-vec3(.6,.75,0),w,vec3(0,-1,.3),.02);"
               "n(z,a-vec3(.6,.75,0),w,vec3(0,-1,-.3),.02);"
               "n(z,a-vec3(-.3,.71,0),w,vec3(.015,.03,.002));"
               "n(z,a-vec3(.3,.71,0),w,vec3(.015,.03,.002));"
               "n(z,a-vec3(-.61,.1,0),w,vec3(.001,.02,.2));"
               "n(z,a-vec3(.61,.1,0),w,vec3(.001,.02,.2));"
               "if(z.w<y.w)"
                 "{"
                   "vec3 v=a+w*z.w;"
                   "y=z;"
                   "m=mat3(vec3(v),vec3(0),vec3(7));"
                   "y.zx*=n(-.2);"
                 "}"
               "z=vec4(100);"
               "n(z,a-vec3(-.6,0,0),w,vec3(.04,.01,.3));"
               "n(z,a-vec3(.6,0,0),w,vec3(.04,.01,.3));"
               "if(z.w<y.w)"
                 "{"
                   "vec3 v=a+w*z.w;"
                   "y=z;"
                   "m=mat3(vec3(v),vec3(0),vec3(8));"
                   "y.zx*=n(-.2);"
                 "}"
               "w.zx*=n(-.2);"
               "a.zx*=n(-.2);"
               "z=vec4(100);"
               "n(z,a-vec3(0,-1,10),w,vec3(1.5,1,100));"
               "if(z.w<y.w)"
                 "y=z,m=mat3(2);"
               "z=vec4(100);"
               "n(z,a+.03,w,vec3(100,0,100));"
               "if(z.w<y.w)"
                 "y=z,m=mat3(0);"
               "z=vec4(100);"
               "n(z,a-vec3(-5,0,10),w,vec3(3.4,3,100));"
               "n(z,a-vec3(5,0,10),w,vec3(3.4,3,100));"
               "n(z,a-vec3(0,0,20),w,vec3(10,10,0));"
               "if(z.w<y.w)"
                 "y=z,m=mat3(1);"
               "a-=vec3(1.6,1.72,0);"
               "z=vec4(100);"
               "n(z,a,w,vec3(.01,.25,.5));"
               "if(z.w<y.w)"
                 "{"
                   "vec3 v=a+w*z.w;"
                   "y=z;"
                   "m=mat3(vec3(v),vec3(0),vec3(9));"
                 "}"
               "a+=vec3(1.6,1.72,0);"
               "z=vec4(100);"
               "n(z,a-vec3(1.6,0,1.4),w,vec3(.02,3,.1));"
               "n(z,a-vec3(-1.6,0,1.4),w,vec3(.02,3,.1));"
               "n(z,a-vec3(1.6,0,-11.4),w,vec3(.02,3,.1));"
               "n(z,a-vec3(-1.6,0,-11.4),w,vec3(.02,3,.1));"
               "n(z,a-vec3(-1.6,.4,-2),w,vec3(.01,.06,.1));"
               "if(z.w<y.w)"
                 "y=z,m=mat3(vec3(.5),vec3(0),vec3(.4,1,0));"
               "z=vec4(100);"
               "n(z,a-vec3(0,2.5,10),w,vec3(100,0,100));"
               "if(z.w<y.w)"
                 "y=z,m=mat3(3);"
               "a.z-=-4.;"
               "z=vec4(100);"
               "n(z,a,w,vec3(2.5));"
               "if(z.w<1e2)"
                 "{"
                   "vec3 v=a;"
                   "float z=0.,f;"
                   "for(int i=0;i++<120;)"
                     "{"
                       "f=t(v)+.001*x.x;"
                       "z+=f;"
                       "v+=f*w;"
                       "if(abs(f)<1e-4||z>y.w)"
                         "break;"
                     "}"
                   "if(abs(f)<.001&&z<y.w)"
                     "{"
                       "vec2 x=vec2(0,.001);"
                       "y=vec4(normalize(vec3(t(v+x.yxx)-t(v-x.yxx),t(v+x.xyx)-t(v-x.xyx),t(v+x.xxy)-t(v-x.xxy))),z);"
                       "m=mat3(vec3(.6,.67,.7),vec3(0),vec3(0,1,4));"
                     "}"
                 "}"
               "a.z+=-4.;"
               "if(y.w>99.)"
                 "break;"
               "mat3 d=n(y.xyz);"
               "vec3 c=a+w*y.w,e=c*d;"
               "if(m[2].z==1)"
                 "if(c.y<.2)"
                   "m=mat3(vec3(.1),vec3(0),vec3(.4,0,0));"
                 "else"
                   "{"
                     "float v=floor(e.y/.1);"
                     "vec2 z=vec2((floor(e.x/.2+mod(v,2.)*.5)-mod(v,2.)*.5)*.2+.1,v*.1+.05);"
                     "vec3 a=n(e.xy-z,vec2(.093,.043),.003),w=s(z.xyy),f=.5+.5*sin(3.*p(c*2.));"
                     "m=mat3(vec3(.1+.4*f.x),vec3(0),vec3(.8,0,0));"
                     "if(a.z<0.)"
                       "{"
                         "m=mat3(pow(vec3(.9,.7,.5),vec3(exp2(.5*w.z))),vec3(0),vec3(.2,0,0));"
                         "if(f.y*.2>x.x)"
                           "m=mat3(vec3(.6*f.x),vec3(0),vec3(.5,0,0));"
                         "y.xyz=normalize(d*vec3(step(abs(a.z),.002)*a.xy+.01*(w.xy-.5),2));"
                       "}"
                   "}"
               "else if(m[2].z==9)"
                 "{"
                   "vec2 v=m[0].zy;"
                   "if(v.x<-.08)"
                     "{"
                       "vec2 z=v.xy*60.+vec2(16,0);"
                       "float w=1.;"
                       "n(z,w,6,0,4,2,1.6);"
                       "n(z,w,4,2,3,2,0);"
                       "n(z,w,3,2,2,6,1.6);"
                       "n(z,w,5,0,4,1,1.6);"
                       "n(z,w,4,1,2,1,0);"
                       "n(z,w,2,1,1,2,-1.6);"
                       "n(z,w,1,2,1,3,0);"
                       "n(z,w,1,3,-1,6,-2.);"
                       "m[0]=length(z)<10.&&(length(z)>8.||abs(z.x+z.y)<1.5)?"
                         "vec3(1,.2,.3):"
                         "w<.3&&z.y>0.||abs(z.x)<6.3&&abs(z.y+1.3)<1.&&abs(z.x-5.5)>.2&&abs(z.x-4.5)>.2?"
                           "vec3(0):"
                           "vec3(1);"
                     "}"
                   "else"
                     "{"
                       "vec2 z=v.xy*80.-vec2(6,0);"
                       "float w=1.;"
                       "n(z,w,-7,6,-1,6,0);"
                       "n(z,w,-4,7,-4,2,0);"
                       "n(z,w,-4,6,-7,2.5,-.2);"
                       "n(z,w,-4,6,-1,2.5,.2);"
                       "n(z,w,1,6,7,6,0);"
                       "n(z,w,4,7,4,2,0);"
                       "n(z,w,4,6,1,2.5,-.2);"
                       "n(z,w,4,6,7,2.5,.2);"
                       "n(z,w,-6,0,6,0,0);"
                       "n(z,w,-7,-2.5,7,-2.5,0);"
                       "n(z,w,0,-2.5,0,-7,0);"
                       "n(z,w,0,-7,-2,-7,0);"
                       "n(z,w,-3,-4.5,-6.5,-7,-.5);"
                       "n(z,w,3,-4.5,6.5,-7,.3);"
                       "z.x-=20.;"
                       "n(z,w,-7,4,-7,0,0);"
                       "n(z,w,-3,3,-4,1,0);"
                       "n(z,w,-5,7,-5,-1,0);"
                       "n(z,w,-5,-1,-7,-7,-.5);"
                       "n(z,w,-5,-1,-3,-4,0);"
                       "n(z,w,-1,7,7,7,0);"
                       "n(z,w,-1,3.5,-1,-1,0);"
                       "n(z,w,-1,3.5,7,3.5,0);"
                       "n(z,w,7,3.5,7,-1,0);"
                       "n(z,w,1.7,7,1.7,-1,0);"
                       "n(z,w,4.3,7,4.3,-1,0);"
                       "n(z,w,-1,-1,7,-1,0);"
                       "n(z,w,0,-4,6,-4,0);"
                       "n(z,w,3,-1,3,-7,0);"
                       "n(z,w,-1,-7,7,-7,0);"
                       "m[0]=w<.8?"
                         "vec3(1,.2,.3):"
                         "vec3(1);"
                     "}"
                   "m=mat3(mix(vec3(.1),vec3(.9),m[0]),vec3(0),vec3(.4,0,1));"
                 "}"
               "else if(m[2].z==2)"
                 "{"
                   "vec2 z=e.xy;"
                   "m=mat3(vec3(.1+.1*sin(3.*p(2.*z.xxy).x)),vec3(0),vec3(.8,0,0));"
                   "vec2 v=floor(z/.3)*.3+.15;"
                   "if(v.x==.15)"
                     "{"
                       "vec3 x=n(z-v,vec2(.135),.01);"
                       "if(x.z<0.)"
                         "{"
                           "m=mat3(vec3(.8,.5,.1),vec3(0),vec3(.1,0,1));"
                           "z-=v;"
                           "z.x-=(floor(z.x/.07)+.5)*.07;"
                           "vec3 a=n(z,vec2(0,.11),.015);"
                           "y.xyz=normalize(d*vec3(step(abs(x.z),.004)*x.xy+step(abs(a.z),.002)*a.xy+.01*s(v.xyy).xy,1));"
                         "}"
                     "}"
                   "else"
                     "{"
                       "v=floor(z/.5)*.5+.25;"
                       "vec3 a=n(z-v,vec2(.235),.01);"
                       "if(a.z<0.)"
                         "m=mat3(vec3(v.x==-.25?"
                           ".2:"
                           ".4),vec3(0),vec3(.4,0,0)),y.xyz=normalize(d*vec3(step(abs(a.z+.002),.002)*a.xy+.01*s(v.xyy).xy,2));"
                       "bool x=z.x<0.;"
                       "z=vec2(abs(abs(z.x)-.68),(z.y-.78)*sign(z.x));"
                       "a=n(z,vec2(.15),.05);"
                       "if((a+.04*max(p(c*10.),0.)).z<0.)"
                         "m=mat3((a.z>-.01||abs(z.x)<.16&&abs(z.x-z.y-.08)<.05)^^x?"
                           "vec3(.1,.1,.3):"
                           "vec3(.9),vec3(0),vec3(.5,0,1));"
                     "}"
                   "if(smoothstep(0.,1.,p(c).y+.3)>x.x)"
                     "m=mat3(0);"
                 "}"
               "else if(m[2].z==3)"
                 "{"
                   "vec2 z=c.xz;"
                   "z-=floor(z/6.+.5)*6.;"
                   "m=abs(z.x)<.7&&abs(z.y)<.2?"
                     "mat3(vec3(.3),vec3(10),vec3(.04,1,0)):"
                     "(z=c.xz,abs((floor(c.z/.2)+.5)*.2-c.z)<.09?"
                       "mat3(vec3(.8),vec3(0),vec3(.4,0,0)):"
                       "mat3(vec3(.02),vec3(0),vec3(.8,0,0)));"
                 "}"
               "else if(m[2].z==5)"
                 "{"
                   "vec2 v=170.*m[0].xy;"
                   "if(abs(v.x)<23.&&abs(v.y)<23.)"
                     "{"
                       "float z=8.;"
                       "n(v,z,-14,3,-9,3,0);"
                       "n(v,z,-9,3,-4,9,0);"
                       "n(v,z,-4,9,6,9,0);"
                       "n(v,z,6,9,10,4,0);"
                       "n(v,z,-1,9,4,0,0);"
                       "n(v,z,4,0,5,-9,0);"
                       "n(v,z,5,-9,14,-9,0);"
                       "n(v,z,-4,8,1,-1,0);"
                       "n(v,z,1,-1,-6,-14,0);"
                       "n(v,z,-5,-18,2,-24,0);"
                       "z=min(z-1.6,length(v-vec2(-4.3,14.4))-3.4);"
                       "z=min(z,min(max(12.-abs(v.x+min(0.,v.y+16.)),sign(v.x)-z),20.-v.y));"
                       "m=mat3(vec3(1),z<0.?"
                         "vec3(0,2,1):"
                         "vec3(2),vec3(.2,1,0));"
                     "}"
                   "else"
                     " m=mat3(vec3(.9),vec3(0),vec3(.4,0,0));"
                 "}"
               "else if(m[2].z==6)"
                 "{"
                   "vec2 z=m[0].xy/vec2(.012,.016);"
                   "float v=m[1].x;"
                   "if(abs(z.y)>16.)"
                     "m=mat3(cos(.6*(z.x-z.y))>0.?"
                       "vec3(1,.5,0):"
                       "vec3(0),vec3(0),vec3(.1,0,0));"
                   "else"
                     "{"
                       "float v=1.;"
                       "z.x+=27.;"
                       "n(z,v,0,7,0,5,0);"
                       "n(z,v,-6,5,6,5,0);"
                       "n(z,v,-4,3,-2,-5,-.1);"
                       "n(z,v,4,3,1,-7,-.3);"
                       "n(z,v,-7,-7,7,-7,0);"
                       "z.x-=18.;"
                       "n(z,v,-3,7,0,7,0);"
                       "n(z,v,0,7,-7,-7,-1.);"
                       "n(z,v,0,7,7,-7,1.);"
                       "z.x-=18.;"
                       "n(z,v,-7,6,-1,6,0);"
                       "n(z,v,-4,7,-4,2,0);"
                       "n(z,v,-4,6,-7,2.5,-.2);"
                       "n(z,v,-4,6,-1,2.5,.2);"
                       "n(z,v,1,6,7,6,0);"
                       "n(z,v,4,7,4,2,0);"
                       "n(z,v,4,6,1,2.5,-.2);"
                       "n(z,v,4,6,7,2.5,.2);"
                       "n(z,v,-6,0,6,0,0);"
                       "n(z,v,-7,-2.5,7,-2.5,0);"
                       "n(z,v,0,-2.5,0,-7,0);"
                       "n(z,v,0,-7,-2,-7,0);"
                       "n(z,v,-3,-4.5,-6.5,-7,-.5);"
                       "n(z,v,3,-4.5,6.5,-7,.3);"
                       "z.x-=18.;"
                       "n(z,v,0,7,0,-7,0);"
                       "n(z,v,0,2,6,2,0);"
                       "n(z,v,-4,3,-4,-7,0);"
                       "n(z,v,-7,-7,7,-7,0);"
                       "m[0]=v<1.?"
                         "vec3(.7,0,0):"
                         "vec3(1);"
                     "}"
                   "v=exp(exp(5.+2.*p(c*4.).y)*max(-.04,v));"
                   "m=mat3(mix(vec3(.04),vec3(.9),m[0])*pow(vec3(.3,.1,.01),vec3(v)),vec3(0),vec3(mix(.2,1.,v),0,1));"
                   "y.xyz=normalize(y.xyz);"
                 "}"
               "else if(m[2].z==7)"
                 "{"
                   "float v=step(.5,p(20.*c).x);"
                   "m=mat3(mix(vec3(.5,.1,.02),vec3(.1,.02,.03),v),vec3(0),vec3(mix(.4,1.,v),0,1));"
                   "y.xyz=normalize(y.xyz+.04*p(80.*c));"
                 "}"
               "else if(m[2].z==8)"
                 "m=mat3(vec3(.3),vec3(0),vec3(.7,1,1));"
               "x=s(x);"
               "if(m[2].z==1)"
                 "if(pow(.5+.5*p(20.*p(c.xyz)).x,8)>x.x)"
                   "m=mat3(vec3(.1,.06,.04),m[1],vec3(1,0,0));"
               "a=c+y.xyz*.001;"
               "float k=m[2].x*m[2].x;"
               "x=s(x);"
               "{"
                 "float B=clamp(dot(y.xyz,-w),0.,1.),r=mix(.04,1.,pow(1.-B,5)),C=max(step(x.x,r),m[2].y);"
                 "v.xyz+=clamp(l,0.,4.)*(1.-r)*m[1];"
                 "x.y=sqrt((1.-x.y)/(1.-C*(1.-k*k)*x.y));"
                 "vec3 u=n(y.xyz)*vec3(sqrt(1.-x.y*x.y)*sin(f*x.z+vec2(0,f/4.)),x.y);"
                 "if(C>0.)"
                   "{"
                     "float z=clamp(dot(y.xyz,reflect(w,u)),0.,1.),v=clamp(dot(y.xyz,u),0.,1.),a=clamp(dot(-w,u),0.,1.),x=.5*k;"
                     "l*=z>0.&&v>0.?"
                       "mix(mix(vec3(.04),m[0],m[2].y),vec3(1),pow(1.-a,5))/mix(r,1.,m[2].y)*z/(z*(1.-x)+x)/(B*(1.-x)+x)*a/v:"
                       "vec3(0);"
                     "u=reflect(w,u);"
                   "}"
                 "else"
                   "{"
                     "if(dot(u,y.xyz)<0.)"
                       "break;"
                     "l*=(1.-mix(.04,1.,pow(1.-clamp(dot(-w,normalize(-w+u)),0.,1.),5)))/(1.-r)*m[0];"
                   "}"
                 "w=u;"
               "}"
               "if(dot(l,l)<.01)"
                 "break;"
             "}"
         "}"
     "}"
   "v.w=10.;"
 "}";

#endif // FRAG_DRAW_H_
