// Generated with Shader Minifier 1.5.1 (https://github.com/laurentlb/Shader_Minifier/)
#ifndef FRAG_DRAW_H_
# define FRAG_DRAW_H_
# define VAR_fragColor "v"
# define VAR_frame "y"
# define VAR_resolution "m"

const char *draw_frag =
 "#version 430\n"
 "layout(location=0)out vec4 v;"
 "layout(location=0)uniform vec4 m;"
 "layout(location=1)uniform int y;"
 "const float z=2*acos(-1);"
 "vec3 f(vec3 v)"
 "{"
   "uvec3 y=floatBitsToUint(v);"
   "y=(y>>16u^y.yzx)*1111111111u;"
   "y=(y>>16u^y.yzx)*1111111111u;"
   "y=(y>>16u^y.yzx)*1111111111u;"
   "return vec3(y)/float(-1u);"
 "}"
 "vec2 f(float v)"
 "{"
   "return vec2(cos(v),sin(v));"
 "}"
 "mat2 s(float v)"
 "{"
   "return mat2(cos(v),sin(v),-sin(v),cos(v));"
 "}"
 "mat3 s(vec3 v)"
 "{"
   "v=normalize(v);"
   "vec3 y=normalize(cross(abs(v.y)<.99?"
     "vec3(0,1,0):"
     "vec3(0,0,1),v));"
   "return mat3(y,cross(v,y),v);"
 "}"
 "vec3 n(vec3 v)"
 "{"
   "vec3 m=vec3(0);"
   "for(int i=0;i++<5;)"
     "v*=2.*s(vec3(3,4,-5)),v+=sin(v.yzx),m=m*2.+cross(cos(v),sin(v.zxy));"
   "return m/31.;"
 "}"
 "vec3 f(vec2 v,vec2 y,float x)"
 "{"
   "y=abs(v)-y;"
   "float z=max(y.x,y.y);"
   "if(z>0.)"
     "{"
       "vec2 z=max(y,0.);"
       "float m=length(z);"
       "return vec3(sign(v)*z/m,m-x);"
     "}"
   "return vec3(sign(v)*step(vec2(z),y),z-x);"
 "}"
 "void f(vec2 v,inout float z,float m,float y,float x,float p,float s)"
 "{"
   "s=s==0.?"
     ".001:"
     "s;"
   "v-=vec2(m,y);"
   "vec2 a=vec2(x-m,p-y),n=f(abs(s)/2.);"
   "m=length(a);"
   "y=m/2./n.y;"
   "v*=mat2(a.y,-a.x,a.x,a.y)/m;"
   "v.x*=sign(s);"
   "v-=y*n*vec2(-1,1);"
   "v.y=abs(v.y);"
   "z=min(z,n.y*v.x>n.x*v.y?"
     "abs(length(v)-y):"
     "length(v-n*y));"
 "}"
 "void f(inout vec4 v,vec3 y,vec3 x,vec3 m)"
 "{"
   "y=-y/x;"
   "m=abs(m/x);"
   "y-=m;"
   "m+=y+m;"
   "float z=max(max(y.x,y.y),y.z),w=min(min(m.x,m.y),m.z);"
   "if(w>=z)"
     "{"
       "if(z>0.&&z<v.w)"
         "v=vec4(-sign(x)*step(vec3(z),y),z);"
       "if(w>0.&&w<v.w)"
         "v=vec4(-sign(x)*step(m,vec3(w)),w);"
     "}"
 "}"
 "void f(inout vec4 v,vec3 y,vec3 x,float z)"
 "{"
   "float m=dot(y,x);"
   "z=m*m-dot(y,y)+z*z;"
   "if(z>0.)"
     "{"
       "z=sqrt(z);"
       "float w=-m-z;"
       "if(w>0.&&w<v.w)"
         "v=vec4(normalize(y+x*w),w);"
       "w=-m+z;"
       "if(w>0.&&w<v.w)"
         "v=vec4(-normalize(y+x*w),w);"
     "}"
 "}"
 "void f(inout vec4 v,vec3 y,vec3 x,vec3 z,float m)"
 "{"
   "float s=dot(z,z),n=dot(z,x),a=dot(y,z),w=s-n*n,p=s*dot(y,x)-a*n,l=p*p-w*(s*dot(y,y)-a*a-m*m*s);"
   "if(l>0.)"
     "{"
       "float d=(-p-sqrt(l))/w;"
       "if(d>0.)"
         "{"
           "float w=clamp(a+d*n,0.,s);"
           "if(w>0.&&w<s&&d<v.w)"
             "v=vec4((y+x*d-w/s*z)/m,d);"
           "f(v,y-clamp(w,0.,s)/s*z,x,m);"
         "}"
     "}"
 "}"
 "float f(float v,float y)"
 "{"
   "float z=max(1.5-abs(v-y),0.)/1.5;"
   "return min(v,y)-z*z*z*1.5/6.;"
 "}"
 "float p(vec3 v)"
 "{"
   "return.8*f(f(length(v+.4*n(v*.5+14.)-vec3(0,1.2,0))-.8,2.5-v.y),length(vec2(v.x-clamp(v.x,-1.5,1.5),v.y)))+.01;"
 "}"
 "void main()"
 "{"
   "v*=0.;"
   "vec2 x=gl_FragCoord.xy/m.xy-.5;"
   "x.x*=m.x/m.y;"
   "if(abs(x.x)<.7)"
     "{"
       "vec3 w=f(vec3(x,y));"
       "for(int i=0;i++<10;)"
         "{"
           "vec2 y=x*s(.01)+w.xy/m.y;"
           "w=f(w);"
           "vec3 a=vec3(-.1,1.6,11),d=normalize(vec3(y,-4));"
           "d.zx*=s(.01);"
           "d.yz*=s(.045);"
           "d=a+d*10.;"
           "a+=.01*vec3(f(z*w.z)*sqrt(w.y),0);"
           "d=normalize(d-a);"
           "vec3 l=vec3(1.2-length(x)*length(x));"
           "for(int i=0;i++<5;)"
             "{"
               "mat3 m;"
               "vec4 y=vec4(100),x=vec4(100);"
               "f(x,a-vec3(0,2.5,-2),d,vec3(.15,.33,.05));"
               "if(x.w<y.w)"
                 "y=x,m=mat3(vec3(a+d*y.w-vec3(0,2.32,-2)),vec3(0),vec3(5));"
               "a.zx*=s(.2);"
               "d.zx*=s(.2);"
               "a-=vec3(0,.4,0);"
               "x=vec4(100);"
               "f(x,a,d,vec3(.45,.3,0));"
               "if(x.w<y.w)"
                 "{"
                   "vec3 v=a+d*x.w;"
                   "float z=max(f(v.xy,vec2(.45,.3),0.).z,-f(abs(abs(v.xy-vec2(0,.28))-vec2(.3,0)),vec2(.015,0),.005).z)+.01*n(8.*v).x;"
                   "if(z<0.)"
                     "y=x,m=mat3(vec3(v),vec3(z),vec3(6)),y.zx*=s(-.2);"
                 "}"
               "a+=vec3(0,.4,0);"
               "x=vec4(100);"
               "f(x,a-vec3(-.6,.75,0),d,vec3(0,-1,.3),.02);"
               "f(x,a-vec3(-.6,.75,0),d,vec3(0,-1,-.3),.02);"
               "f(x,a-vec3(-.6,.75,0),d,vec3(1.2,0,0),.02);"
               "f(x,a-vec3(-.6,.1,.19),d,vec3(1.2,0,0),.01);"
               "f(x,a-vec3(-.6,.1,-.19),d,vec3(1.2,0,0),.01);"
               "f(x,a-vec3(.6,.75,0),d,vec3(0,-1,.3),.02);"
               "f(x,a-vec3(.6,.75,0),d,vec3(0,-1,-.3),.02);"
               "f(x,a-vec3(-.3,.71,0),d,vec3(.015,.03,.002));"
               "f(x,a-vec3(.3,.71,0),d,vec3(.015,.03,.002));"
               "f(x,a-vec3(-.61,.1,0),d,vec3(.001,.02,.2));"
               "f(x,a-vec3(.61,.1,0),d,vec3(.001,.02,.2));"
               "if(x.w<y.w)"
                 "{"
                   "vec3 v=a+d*x.w;"
                   "y=x;"
                   "m=mat3(vec3(v),vec3(0),vec3(7));"
                   "y.zx*=s(-.2);"
                 "}"
               "x=vec4(100);"
               "f(x,a-vec3(-.6,0,0),d,vec3(.04,.01,.3));"
               "f(x,a-vec3(.6,0,0),d,vec3(.04,.01,.3));"
               "if(x.w<y.w)"
                 "{"
                   "vec3 v=a+d*x.w;"
                   "y=x;"
                   "m=mat3(vec3(v),vec3(0),vec3(8));"
                   "y.zx*=s(-.2);"
                 "}"
               "d.zx*=s(-.2);"
               "a.zx*=s(-.2);"
               "x=vec4(100);"
               "f(x,a-vec3(0,-1,10),d,vec3(1.5,1,100));"
               "if(x.w<y.w)"
                 "y=x,m=mat3(2);"
               "x=vec4(100);"
               "f(x,a+.03,d,vec3(100,0,100));"
               "if(x.w<y.w)"
                 "y=x,m=mat3(0);"
               "x=vec4(100);"
               "f(x,a-vec3(-5,0,10),d,vec3(3.4,3,100));"
               "f(x,a-vec3(5,0,10),d,vec3(3.4,3,100));"
               "f(x,a-vec3(0,0,20),d,vec3(10,10,0));"
               "if(x.w<y.w)"
                 "y=x,m=mat3(1);"
               "a-=vec3(1.6,1.72,0);"
               "x=vec4(100);"
               "f(x,a,d,vec3(.01,.25,.5));"
               "if(x.w<y.w)"
                 "{"
                   "vec3 v=a+d*x.w;"
                   "y=x;"
                   "m=mat3(vec3(v),vec3(0),vec3(9));"
                 "}"
               "a+=vec3(1.6,1.72,0);"
               "x=vec4(100);"
               "f(x,a-vec3(1.6,0,1.4),d,vec3(.02,3,.1));"
               "f(x,a-vec3(-1.6,0,1.4),d,vec3(.02,3,.1));"
               "f(x,a-vec3(1.6,0,-11.4),d,vec3(.02,3,.1));"
               "f(x,a-vec3(-1.6,0,-11.4),d,vec3(.02,3,.1));"
               "f(x,a-vec3(-1.6,.4,-2),d,vec3(.01,.06,.1));"
               "if(x.w<y.w)"
                 "y=x,m=mat3(vec3(.5),vec3(0),vec3(.4,1,0));"
               "x=vec4(100);"
               "f(x,a-vec3(0,2.5,10),d,vec3(100,0,100));"
               "if(x.w<y.w)"
                 "y=x,m=mat3(3);"
               "a.z-=-4.;"
               "x=vec4(100);"
               "f(x,a,d,vec3(2.5));"
               "if(x.w<1e2)"
                 "{"
                   "vec3 v=a;"
                   "float z=0.,x;"
                   "for(int i=0;i++<120;)"
                     "{"
                       "x=p(v)+.001*w.x;"
                       "z+=x;"
                       "v+=x*d;"
                       "if(abs(x)<1e-4||z>y.w)"
                         "break;"
                     "}"
                   "if(abs(x)<.001&&z<y.w)"
                     "{"
                       "vec2 x=vec2(0,.001);"
                       "y=vec4(normalize(vec3(p(v+x.yxx)-p(v-x.yxx),p(v+x.xyx)-p(v-x.xyx),p(v+x.xxy)-p(v-x.xxy))),z);"
                       "m=mat3(vec3(.6,.67,.7),vec3(0),vec3(0,1,4));"
                     "}"
                 "}"
               "a.z+=-4.;"
               "if(y.w>99.)"
                 "break;"
               "mat3 c=s(y.xyz);"
               "vec3 e=a+d*y.w,r=e*c;"
               "if(m[2].z==1)"
                 "if(e.y<.2)"
                   "m=mat3(vec3(.1),vec3(0),vec3(.4,0,0));"
                 "else"
                   "{"
                     "float v=floor(r.y/.1);"
                     "vec2 x=vec2((floor(r.x/.2+mod(v,2.)*.5)-mod(v,2.)*.5)*.2+.1,v*.1+.05);"
                     "vec3 z=f(r.xy-x,vec2(.093,.043),.003),a=f(x.xyy),d=.5+.5*sin(3.*n(e*2.));"
                     "m=mat3(vec3(.1+.4*d.x),vec3(0),vec3(.8,0,0));"
                     "if(z.z<0.)"
                       "{"
                         "m=mat3(pow(vec3(.9,.7,.5),vec3(exp2(.5*a.z))),vec3(0),vec3(.2,0,0));"
                         "if(d.y*.2>w.x)"
                           "m=mat3(vec3(.6*d.x),vec3(0),vec3(.5,0,0));"
                         "y.xyz=normalize(c*vec3(step(abs(z.z),.002)*z.xy+.01*(a.xy-.5),2));"
                       "}"
                   "}"
               "else if(m[2].z==9)"
                 "{"
                   "vec2 v=m[0].zy;"
                   "if(v.x<-.08)"
                     "{"
                       "vec2 x=v.xy*60.+vec2(16,0);"
                       "float d=1.;"
                       "f(x,d,6,0,4,2,1.6);"
                       "f(x,d,4,2,3,2,0);"
                       "f(x,d,3,2,2,6,1.6);"
                       "f(x,d,5,0,4,1,1.6);"
                       "f(x,d,4,1,2,1,0);"
                       "f(x,d,2,1,1,2,-1.6);"
                       "f(x,d,1,2,1,3,0);"
                       "f(x,d,1,3,-1,6,-2.);"
                       "m[0]=length(x)<10.&&(length(x)>8.||abs(x.x+x.y)<1.5)?"
                         "vec3(1,.2,.3):"
                         "d<.3&&x.y>0.||abs(x.x)<6.3&&abs(x.y+1.3)<1.&&abs(x.x-5.5)>.2&&abs(x.x-4.5)>.2?"
                           "vec3(0):"
                           "vec3(1);"
                     "}"
                   "else"
                     "{"
                       "vec2 x=v.xy*80.-vec2(6,0);"
                       "float d=1.;"
                       "f(x,d,-7,6,-1,6,0);"
                       "f(x,d,-4,7,-4,2,0);"
                       "f(x,d,-4,6,-7,2.5,-.2);"
                       "f(x,d,-4,6,-1,2.5,.2);"
                       "f(x,d,1,6,7,6,0);"
                       "f(x,d,4,7,4,2,0);"
                       "f(x,d,4,6,1,2.5,-.2);"
                       "f(x,d,4,6,7,2.5,.2);"
                       "f(x,d,-6,0,6,0,0);"
                       "f(x,d,-7,-2.5,7,-2.5,0);"
                       "f(x,d,0,-2.5,0,-7,0);"
                       "f(x,d,0,-7,-2,-7,0);"
                       "f(x,d,-3,-4.5,-6.5,-7,-.5);"
                       "f(x,d,3,-4.5,6.5,-7,.3);"
                       "x.x-=20.;"
                       "f(x,d,-7,4,-7,0,0);"
                       "f(x,d,-3,3,-4,1,0);"
                       "f(x,d,-5,7,-5,-1,0);"
                       "f(x,d,-5,-1,-7,-7,-.5);"
                       "f(x,d,-5,-1,-3,-4,0);"
                       "f(x,d,-1,7,7,7,0);"
                       "f(x,d,-1,3.5,-1,-1,0);"
                       "f(x,d,-1,3.5,7,3.5,0);"
                       "f(x,d,7,3.5,7,-1,0);"
                       "f(x,d,1.7,7,1.7,-1,0);"
                       "f(x,d,4.3,7,4.3,-1,0);"
                       "f(x,d,-1,-1,7,-1,0);"
                       "f(x,d,0,-4,6,-4,0);"
                       "f(x,d,3,-1,3,-7,0);"
                       "f(x,d,-1,-7,7,-7,0);"
                       "m[0]=d<.8?"
                         "vec3(1,.2,.3):"
                         "vec3(1);"
                     "}"
                   "m=mat3(mix(vec3(.1),vec3(.9),m[0]),vec3(0),vec3(.4,0,1));"
                 "}"
               "else if(m[2].z==2)"
                 "{"
                   "vec2 x=r.xy;"
                   "m=mat3(vec3(.1+.1*sin(3.*n(2.*x.xxy).x)),vec3(0),vec3(.8,0,0));"
                   "vec2 v=floor(x/.3)*.3+.15;"
                   "if(v.x==.15)"
                     "{"
                       "vec3 z=f(x-v,vec2(.135),.01);"
                       "if(z.z<0.)"
                         "{"
                           "m=mat3(vec3(.8,.5,.1),vec3(0),vec3(.1,0,1));"
                           "x-=v;"
                           "x.x-=(floor(x.x/.07)+.5)*.07;"
                           "vec3 w=f(x,vec2(0,.11),.015);"
                           "y.xyz=normalize(c*vec3(step(abs(z.z),.004)*z.xy+step(abs(w.z),.002)*w.xy+.01*f(v.xyy).xy,1));"
                         "}"
                     "}"
                   "else"
                     "{"
                       "v=floor(x/.5)*.5+.25;"
                       "vec3 z=f(x-v,vec2(.235),.01);"
                       "if(z.z<0.)"
                         "m=mat3(vec3(v.x==-.25?"
                           ".2:"
                           ".4),vec3(0),vec3(.4,0,0)),y.xyz=normalize(c*vec3(step(abs(z.z+.002),.002)*z.xy+.01*f(v.xyy).xy,2));"
                       "bool w=x.x>0.;"
                       "x=vec2(abs(abs(x.x)-.68),(x.y-.78)*sign(x.x));"
                       "z=f(x,vec2(.15),.05);"
                       "if((z+.04*max(n(e*10.),0.)).z<0.)"
                         "m=mat3((z.z>-.01||abs(x.x)<.16&&abs(x.x-x.y-.08)<.05)^^w?"
                           "vec3(.1,.1,.3):"
                           "vec3(.9),vec3(0),vec3(.5,0,1));"
                     "}"
                   "if(smoothstep(0.,1.,.2-n(e).y)>w.x)"
                     "m=mat3(0);"
                 "}"
               "else if(m[2].z==3)"
                 "{"
                   "vec2 x=e.xz;"
                   "x-=floor(x/6.+.5)*6.;"
                   "if(abs(x.x)<.7&&abs(x.y)<.2)"
                     "m=mat3(vec3(.3),vec3(10),vec3(.04,1,0));"
                   "else"
                     "{"
                       "x=e.xz;"
                       "float v=(floor(e.z/.2)+.5)*.2-e.z;"
                       "if(abs(v)<.09)"
                         "m=mat3(vec3(.8),vec3(0),vec3(.3,0,0)),y.xyz=normalize(y.xyz-vec3(0,0,v));"
                       "else"
                         " m=mat3(vec3(.02),vec3(0),vec3(.8,0,0));"
                     "}"
                 "}"
               "else if(m[2].z==5)"
                 "{"
                   "vec2 v=170.*m[0].xy;"
                   "if(abs(v.x)<23.&&abs(v.y)<23.)"
                     "{"
                       "float x=8.;"
                       "f(v,x,-14,3,-9,3,0);"
                       "f(v,x,-9,3,-4,9,0);"
                       "f(v,x,-4,9,6,9,0);"
                       "f(v,x,6,9,10,4,0);"
                       "f(v,x,-1,9,4,0,0);"
                       "f(v,x,4,0,5,-9,0);"
                       "f(v,x,5,-9,14,-9,0);"
                       "f(v,x,-4,8,1,-1,0);"
                       "f(v,x,1,-1,-6,-14,0);"
                       "f(v,x,-5,-18,2,-24,0);"
                       "x=min(x-1.6,length(v-vec2(-4.3,14.4))-3.4);"
                       "x=min(x,min(max(12.-abs(v.x+min(0.,v.y+16.)),sign(v.x)-x),20.-v.y));"
                       "m=mat3(vec3(1),x<0.?"
                         "vec3(0,2,1):"
                         "vec3(2),vec3(.2,1,0));"
                     "}"
                   "else"
                     " m=mat3(vec3(.9),vec3(0),vec3(.4,0,0));"
                 "}"
               "else if(m[2].z==6)"
                 "{"
                   "vec2 x=m[0].xy/vec2(.012,.016);"
                   "float v=m[1].x;"
                   "if(abs(x.y)>16.)"
                     "m=mat3(cos(.6*(x.x-x.y))>0.?"
                       "vec3(1,.5,0):"
                       "vec3(0),vec3(0),vec3(.1,0,0));"
                   "else"
                     "{"
                       "float v=1.;"
                       "x.x+=27.;"
                       "f(x,v,0,7,0,5,0);"
                       "f(x,v,-6,5,6,5,0);"
                       "f(x,v,-4,3,-2,-5,-.1);"
                       "f(x,v,4,3,1,-7,-.3);"
                       "f(x,v,-7,-7,7,-7,0);"
                       "x.x-=18.;"
                       "f(x,v,-3,7,0,7,0);"
                       "f(x,v,0,7,-7,-7,-1.);"
                       "f(x,v,0,7,7,-7,1.);"
                       "x.x-=18.;"
                       "f(x,v,-7,6,-1,6,0);"
                       "f(x,v,-4,7,-4,2,0);"
                       "f(x,v,-4,6,-7,2.5,-.2);"
                       "f(x,v,-4,6,-1,2.5,.2);"
                       "f(x,v,1,6,7,6,0);"
                       "f(x,v,4,7,4,2,0);"
                       "f(x,v,4,6,1,2.5,-.2);"
                       "f(x,v,4,6,7,2.5,.2);"
                       "f(x,v,-6,0,6,0,0);"
                       "f(x,v,-7,-2.5,7,-2.5,0);"
                       "f(x,v,0,-2.5,0,-7,0);"
                       "f(x,v,0,-7,-2,-7,0);"
                       "f(x,v,-3,-4.5,-6.5,-7,-.5);"
                       "f(x,v,3,-4.5,6.5,-7,.3);"
                       "x.x-=18.;"
                       "f(x,v,0,7,0,-7,0);"
                       "f(x,v,0,2,6,2,0);"
                       "f(x,v,-4,3,-4,-7,0);"
                       "f(x,v,-7,-7,7,-7,0);"
                       "m[0]=v<1.?"
                         "vec3(.7,0,0):"
                         "vec3(1);"
                     "}"
                   "v=exp(exp(5.+2.*n(e*4.).y)*max(-.04,v));"
                   "m=mat3(mix(vec3(.04),vec3(.9),m[0])*pow(vec3(.3,.1,.01),vec3(v)),vec3(0),vec3(mix(.2,1.,v),0,1));"
                   "y.xyz=normalize(y.xyz);"
                 "}"
               "else if(m[2].z==7)"
                 "{"
                   "float v=step(.5,n(20.*e).x);"
                   "m=mat3(mix(vec3(.5,.1,.02),vec3(.1,.02,.03),v),vec3(0),vec3(mix(.4,1.,v),0,1));"
                   "y.xyz=normalize(y.xyz+.04*n(80.*e));"
                 "}"
               "else if(m[2].z==8)"
                 "m=mat3(vec3(.3),vec3(0),vec3(.7,1,1));"
               "w=f(w);"
               "if(m[2].z==1)"
                 "if(pow(.5+.5*n(20.*n(e.xyz)).x,8)>w.x)"
                   "m=mat3(vec3(.1,.06,.04),m[1],vec3(1,0,0));"
               "a=e+y.xyz*.001;"
               "float k=m[2].x*m[2].x;"
               "w=f(w);"
               "{"
                 "float B=clamp(dot(y.xyz,-d),0.,1.),u=mix(.04,1.,pow(1.-B,5)),C=max(step(w.x,u),m[2].y);"
                 "v.xyz+=clamp(l,0.,4.)*(1.-u)*m[1];"
                 "w.y=sqrt((1.-w.y)/(1.-C*(1.-k*k)*w.y));"
                 "vec3 b=s(y.xyz)*vec3(sqrt(1.-w.y*w.y)*sin(z*w.z+vec2(0,z/4.)),w.y);"
                 "if(C>0.)"
                   "{"
                     "float x=clamp(dot(y.xyz,reflect(d,b)),0.,1.),v=clamp(dot(y.xyz,b),0.,1.),z=clamp(dot(-d,b),0.,1.),w=.5*k;"
                     "l*=x>0.&&v>0.?"
                       "mix(mix(vec3(.04),m[0],m[2].y),vec3(1),pow(1.-z,5))/mix(u,1.,m[2].y)*x/(x*(1.-w)+w)/(B*(1.-w)+w)*z/v:"
                       "vec3(0);"
                     "b=reflect(d,b);"
                   "}"
                 "else"
                   "{"
                     "if(dot(b,y.xyz)<0.)"
                       "break;"
                     "l*=(1.-mix(.04,1.,pow(1.-clamp(dot(-d,normalize(-d+b)),0.,1.),5)))/(1.-u)*m[0];"
                   "}"
                 "d=b;"
               "}"
               "if(dot(l,l)<.01)"
                 "break;"
             "}"
         "}"
     "}"
   "v.w=10.;"
 "}";

#endif // FRAG_DRAW_H_
