// Generated with Shader Minifier 1.3.6 (https://github.com/laurentlb/Shader_Minifier/)
#ifndef FRAG_DRAW_H_
# define FRAG_DRAW_H_
# define VAR_fragColor "v"
# define VAR_frame "y"
# define VAR_resolution "m"

const char *draw_frag =
 "#version 430\n"
 "layout(location=0) out vec4 v;"
 "layout(location=0) uniform vec4 m;"
 "layout(location=1) uniform int y;"
 "const float z=acos(-1.),x=z+z,w=sqrt(.5);"
 "uvec3 i;"
 "vec3 f(vec3 v)"
 "{"
   "uvec3 i=floatBitsToUint(v);"
   "i=(i>>16u^i.yzx)*1111111111u;"
   "i=(i>>16u^i.yzx)*1111111111u;"
   "i=(i>>16u^i.yzx)*1111111111u;"
   "return vec3(i)/float(-1u);"
 "}"
 "vec2 s(float v)"
 "{"
   "return vec2(cos(v),sin(v));"
 "}"
 "mat2 t(float v)"
 "{"
   "return mat2(cos(v),sin(v),-sin(v),cos(v));"
 "}"
 "mat3 n(vec3 v)"
 "{"
   "v=normalize(v);"
   "vec3 z=abs(v.y)<.99?"
     "vec3(0,1,0):"
     "vec3(0,0,1),x=normalize(cross(z,v));"
   "return mat3(x,cross(v,x),v);"
 "}"
 "vec3 p(vec3 v)"
 "{"
   "vec3 m=vec3(0);"
   "for(int i=0;i++<5;)"
     "v*=2.*n(vec3(3,4,-5)),v+=sin(v.yzx),m=m*2.+cross(cos(v),sin(v.zxy));"
   "return m/31.;"
 "}"
 "vec3 f(vec2 v,vec2 i,float y)"
 "{"
   "vec2 x=abs(v)-i;"
   "float z=max(x.x,x.y);"
   "if(z>0.)"
     "{"
       "vec2 m=max(x,0.);"
       "float f=length(m);"
       "return vec3(sign(v)*m/f,f-y);"
     "}"
   "return vec3(sign(v)*step(vec2(z),x),z-y);"
 "}"
 "void f(vec2 v,inout float i,float m,float x,float y,float f,float z)"
 "{"
   "v-=vec2(m,x);"
   "vec2 w=vec2(y-m,f-x);"
   "z=z==0.?"
     ".001:"
     "z;"
   "vec2 n=s(abs(z)/2.);"
   "float t=length(w),p=t/2./n.y;"
   "v*=mat2(w.y,-w.x,w.x,w.y)/t;"
   "v.x*=sign(z);"
   "v-=p*n*vec2(-1,1);"
   "v.y=abs(v.y);"
   "float a=n.y*v.x>n.x*v.y?"
     "abs(length(v)-p):"
     "length(v-n*p);"
   "i=min(i,a);"
 "}"
 "vec4 n(vec3 v,vec3 i,vec3 x)"
 "{"
   "float w=-dot(v,x)/dot(i,x);"
   "return w<0.?"
     "vec4(100):"
     "vec4(x,w);"
 "}"
 "vec4 p(vec3 v,vec3 x,vec3 y)"
 "{"
   "vec3 m=-v/x,z=abs(y/x),w=m-z,i=m+z;"
   "float f=max(max(w.x,w.y),w.z),a=min(min(i.x,i.y),i.z);"
   "return a<f?"
     "vec4(100):"
     "f>0.?"
       "vec4(-sign(x)*step(vec3(f),w),f):"
       "a>0.?"
         "vec4(-sign(x)*step(i,vec3(a)),a):"
         "vec4(100);"
 "}"
 "vec4 s(vec3 v,vec3 x,float y)"
 "{"
   "float m=dot(v,x),w=m*m-dot(v,v)+y*y;"
   "if(w<0.)"
     "return vec4(100);"
   "w=sqrt(w);"
   "float i=-m-w;"
   "if(i>0.)"
     "return vec4(normalize(v+x*i),i);"
   "i=-m+w;"
   "return i>0.?"
     "vec4(-normalize(v+x*i),i):"
     "vec4(100);"
 "}"
 "vec4 f(vec3 v,vec3 x,vec3 y,float i)"
 "{"
   "float m=dot(y,y),z=dot(y,x),w=dot(v,y),f=m-z*z,n=m*dot(v,x)-w*z,a=n*n-f*(m*dot(v,v)-w*w-i*i*m);"
   "if(a<0.)"
     "return vec4(100);"
   "float p=(-n-sqrt(a))/f;"
   "if(p<0.)"
     "return vec4(100);"
   "float d=clamp(w+p*z,0.,m);"
   "return d>0.&&d<m?"
     "vec4((v+x*p-d/m*y)/i,p):"
     "s(v-clamp(d,0.,m)/m*y,x,i);"
 "}"
 "float f(float v,float x)"
 "{"
   "float z=max(2.-abs(v-x),0.)/2.;"
   "return min(v,x)-z*z*z*2./6.;"
 "}"
 "float a(vec3 v)"
 "{"
   "return.9*f(length(v+.1*p(v+14.)-vec3(0,1.2,0))-.8,v.y);"
 "}"
 "void main()"
 "{"
   "v*=0.;"
   "vec2 z=gl_FragCoord.xy/m.xy,i=z-.5;"
   "i.x*=m.x/m.y;"
   "vec3 d=f(vec3(i,y));"
   "for(int r=0;r++<10;)"
     "{"
       "vec2 l=i*t(.01)+d.xy/m.y;"
       "d=f(d);"
       "vec3 c=vec3(-1.2,1.6,11),e=normalize(vec3(l,-4));"
       "e.zx*=t(.12);"
       "e.yz*=t(.04);"
       "vec3 u=c+e*10.;"
       "c+=.01*vec3(s(x*d.z)*sqrt(d.y),0);"
       "e=normalize(u-c);"
       "vec3 b=vec3(2.-length(i));"
       "for(int o=0;o++<5;)"
         "{"
           "mat3 k;"
           "vec4 B=vec4(100),g,C;"
           "g=s(c-vec3(3,2.5,-6),e,.5);"
           "if(g.w<B.w)"
             "B=g,k=mat3(vec3(0),vec3(9,0,0),vec3(1,1,0));"
           "g=p(c-vec3(0,2.35,-2),e,vec3(.15,.15,.05));"
           "if(g.w<B.w)"
             "B=g,k=mat3(vec3(0),vec3(1,4,1),vec3(1,1,0));"
           "c.zx*=t(.2);"
           "e.zx*=t(.2);"
           "c-=vec3(0,.4,0);"
           "g=p(c,e,vec3(.45,.3,0));"
           "if(g.w<B.w)"
             "{"
               "vec3 D=c+e*g.w;"
               "float A=max(f(D.xy,vec2(.45,.3),0.).z,-f(abs(abs(D.xy-vec2(0,.28))-vec2(.3,0)),vec2(.015,0),.01).z)+.01*p(10.*D).x;"
               "if(A<0.)"
                 "B=g,k=mat3(vec3(D),vec3(0),vec3(7)),B.zx*=t(-.2);"
             "}"
           "c+=vec3(0,.4,0);"
           "g=f(c-vec3(-.6,.75,0),e,vec3(0,-1,.3),.02);"
           "C=f(c-vec3(-.6,.75,0),e,vec3(0,-1,-.3),.02);"
           "g=g.w<C.w?"
             "g:"
             "C;"
           "C=f(c-vec3(-.6,.75,0),e,vec3(1.2,0,0),.02);"
           "g=g.w<C.w?"
             "g:"
             "C;"
           "C=f(c-vec3(-.6,.1,.19),e,vec3(1.2,0,0),.01);"
           "g=g.w<C.w?"
             "g:"
             "C;"
           "C=f(c-vec3(-.6,.1,-.19),e,vec3(1.2,0,0),.01);"
           "g=g.w<C.w?"
             "g:"
             "C;"
           "C=f(c-vec3(.6,.75,0),e,vec3(0,-1,.3),.02);"
           "g=g.w<C.w?"
             "g:"
             "C;"
           "C=f(c-vec3(.6,.75,0),e,vec3(0,-1,-.3),.02);"
           "g=g.w<C.w?"
             "g:"
             "C;"
           "C=p(c-vec3(-.3,.71,0),e,vec3(.015,.03,.002));"
           "g=g.w<C.w?"
             "g:"
             "C;"
           "C=p(c-vec3(.3,.71,0),e,vec3(.015,.03,.002));"
           "g=g.w<C.w?"
             "g:"
             "C;"
           "C=p(c-vec3(-.61,.1,0),e,vec3(.001,.02,.2));"
           "g=g.w<C.w?"
             "g:"
             "C;"
           "C=p(c-vec3(.61,.1,0),e,vec3(.001,.02,.2));"
           "g=g.w<C.w?"
             "g:"
             "C;"
           "if(g.w<B.w)"
             "{"
               "B=g;"
               "vec3 D=c+e*B.w;"
               "k=mat3(vec3(D),vec3(0),vec3(8));"
               "B.zx*=t(-.2);"
             "}"
           "g=p(c-vec3(-.6,0,0),e,vec3(.04,.01,.3));"
           "C=p(c-vec3(.6,0,0),e,vec3(.04,.01,.3));"
           "g=g.w<C.w?"
             "g:"
             "C;"
           "if(g.w<B.w)"
             "{"
               "B=g;"
               "vec3 D=c+e*B.w;"
               "k=mat3(vec3(D),vec3(0),vec3(9));"
               "B.zx*=t(-.2);"
             "}"
           "e.zx*=t(-.2);"
           "c.zx*=t(-.2);"
           "g=n(c,e,vec3(0,1,0));"
           "if(g.w<B.w)"
             "B=g,k=mat3(3.);"
           "g=p(c-vec3(-5,0,6),e,vec3(3.5,3,9));"
           "C=p(c-vec3(5,0,6),e,vec3(3.5,3,9));"
           "g=g.w<C.w?"
             "g:"
             "C;"
           "C=p(c-vec3(0,0,20),e,vec3(10,10,0));"
           "g=g.w<C.w?"
             "g:"
             "C;"
           "if(g.w<B.w)"
             "B=g,k=mat3(1.);"
           "c-=vec3(1.5,1.72,0);"
           "g=p(c,e,vec3(.01,.25,.5));"
           "if(g.w<B.w)"
             "{"
               "B=g;"
               "vec3 D=c+e*B.w;"
               "k=mat3(vec3(D),vec3(0),vec3(11));"
             "}"
           "c+=vec3(1.5,1.72,0);"
           "g=p(c-vec3(1.5,0,1.5),e,vec3(.01,3,.1));"
           "C=p(c-vec3(-1.5,0,1.5),e,vec3(.01,3,.1));"
           "g=g.w<C.w?"
             "g:"
             "C;"
           "if(g.w<B.w)"
             "B=g,k=mat3(10.);"
           "g=n(c-vec3(0,0,-9),e,vec3(0,0,1));"
           "C=n(c-vec3(0,2.2,-9),e,vec3(0,-w,w));"
           "g=g.w<C.w?"
             "g:"
             "C;"
           "if(g.w<B.w)"
             "B=g,k=mat3(2.);"
           "g=n(c-vec3(0,2.5,0),e,vec3(0,-1,0));"
           "if(g.w<B.w)"
             "B=g,k=mat3(4.);"
           "c.z-=-7.;"
           "g=s(c,e,2.5);"
           "if(g.w<B.w)"
             "{"
               "vec3 D=c;"
               "float A=0.,E;"
               "for(int F=0;F++<80;)"
                 "{"
                   "E=a(D);"
                   "A+=E;"
                   "D+=E*e;"
                   "if(abs(E)<1e-4||A>B.w)"
                     "break;"
                 "}"
               "if(abs(E)<.001&&A<B.w)"
                 "{"
                   "vec2 F=vec2(0,.001);"
                   "B=vec4(normalize(vec3(a(D+F.yxx)-a(D-F.yxx),a(D+F.xyx)-a(D-F.xyx),a(D+F.xxy)-a(D-F.xxy))),A);"
                   "k=mat3(mix(vec3(0),vec3(.6,.68,.7),smoothstep(0.,.5,D.y)),vec3(0),vec3(.04,1,5));"
                 "}"
             "}"
           "c.z+=-7.;"
           "if(B.w>99.)"
             "break;"
           "mat3 D=n(B.xyz);"
           "vec3 F=c+e*B.w,E=F*D;"
           "if(k[2].z==1.)"
             "if(F.y<.2)"
               "k=mat3(vec3(.1),vec3(0),vec3(.4,0,0));"
             "else"
               "{"
                 "float A=floor(E.y/.1);"
                 "vec2 G=vec2((floor(E.x/.2+mod(A,2.)*.5)-mod(A,2.)*.5)*.2+.1,A*.1+.05);"
                 "vec3 H=f(E.xy-G,vec2(.095,.045),.003)+.002*max(p(20.*E).x,0.),I=f(G.xyy),J=.5+.5*sin(3.*p(F));"
                 "k=mat3(vec3(10.*length(G-E.xy)),vec3(0),vec3(.8,0,0));"
                 "k=mat3(vec3(.1+.6*J.x),vec3(0),vec3(.8,0,0));"
                 "if(H.z<0.)"
                   "k=mat3(mix(pow(vec3(.9,.7,.5),vec3(exp2(.5*I.z))),vec3(.6*J.x),.1*J.y),vec3(0),vec3(.2+.3*J.y,0,0)),B.xyz=normalize(D*vec3(step(abs(H.z+.002),.002)*H.xy+.03*(I.xy-.5),1));"
               "}"
           "else if(k[2].z==2.)"
             "k=mat3(vec3(.9,.8,.6),vec3(0),vec3(.3,0,0)),B.xyz=normalize(B.xyz+.1*p(8.*p(4.*F)));"
           "else if(k[2].z==10.)"
             "k=mat3(vec3(.5),vec3(0),vec3(.4,1,0));"
           "else if(k[2].z==11.)"
             "{"
               "vec2 A=k[0].zy;"
               "if(A.x<-.08)"
                 "{"
                   "vec2 H=A.xy*60.+vec2(16,0);"
                   "float G=1.;"
                   "f(H,G,6,0,4,2,1.6);"
                   "f(H,G,4,2,3,2,0);"
                   "f(H,G,3,2,2,6,1.6);"
                   "f(H,G,5,0,4,1,1.6);"
                   "f(H,G,4,1,2,1,0);"
                   "f(H,G,2,1,1,2,-1.6);"
                   "f(H,G,1,2,1,3,0);"
                   "f(H,G,1,3,-1,6,-2.);"
                   "k[0]=length(H)<10.&&(length(H)>8.||abs(H.x+H.y)<1.5)?"
                     "vec3(1,.2,.3):"
                     "G<.3&&H.y>0.||abs(H.x)<6.3&&abs(H.y+1.3)<1.&&abs(H.x-5.5)>.2&&abs(H.x-4.5)>.2?"
                       "vec3(0):"
                       "vec3(1);"
                 "}"
               "else"
                 "{"
                   "vec2 H=A.xy*80.-vec2(6,0);"
                   "float G=1.;"
                   "f(H,G,-7,6,-1,6,0);"
                   "f(H,G,-4,7,-4,2,0);"
                   "f(H,G,-4,6,-7,2.5,-.2);"
                   "f(H,G,-4,6,-1,2.5,.2);"
                   "f(H,G,1,6,7,6,0);"
                   "f(H,G,4,7,4,2,0);"
                   "f(H,G,4,6,1,2.5,-.2);"
                   "f(H,G,4,6,7,2.5,.2);"
                   "f(H,G,-6,0,6,0,0);"
                   "f(H,G,-7,-2.5,7,-2.5,0);"
                   "f(H,G,0,-2.5,0,-7,0);"
                   "f(H,G,0,-7,-2,-7,0);"
                   "f(H,G,-3,-4.5,-6.5,-7,-.5);"
                   "f(H,G,3,-4.5,6.5,-7,.3);"
                   "H.x-=20.;"
                   "f(H,G,-7,4,-7,0,0);"
                   "f(H,G,-3,3,-4,1,0);"
                   "f(H,G,-5,7,-5,-1,0);"
                   "f(H,G,-5,-1,-7,-7,-.5);"
                   "f(H,G,-5,-1,-3,-4,0);"
                   "f(H,G,-1,7,7,7,0);"
                   "f(H,G,-1,3.5,-1,-1,0);"
                   "f(H,G,-1,3.5,7,3.5,0);"
                   "f(H,G,7,3.5,7,-1,0);"
                   "f(H,G,1.7,7,1.7,-1,0);"
                   "f(H,G,4.3,7,4.3,-1,0);"
                   "f(H,G,-1,-1,7,-1,0);"
                   "f(H,G,0,-4,6,-4,0);"
                   "f(H,G,3,-1,3,-7,0);"
                   "f(H,G,-1,-7,7,-7,0);"
                   "k[0]=G<.8?"
                     "vec3(1,.2,.3):"
                     "vec3(1);"
                 "}"
               "k=mat3(mix(vec3(.1),vec3(.9),k[0]),vec3(0),vec3(.4,0,20));"
             "}"
           "else if(k[2].z==3.)"
             "{"
               "vec2 H=E.xy,G=floor(H/.5)*.5+.25;"
               "vec3 A=f(H-G,vec2(.235),.01),J=f(G.yxx);"
               "k=A.z>0.?"
                 "mat3(vec3(.1+.1*sin(3.*p(2.*H.xxy).x)),vec3(0),vec3(.8,0,0)):"
                 "mat3(vec3(G.x==-.25?"
                   ".2:"
                   ".4),vec3(0),vec3(.4,0,0));"
               "B.xyz=normalize(D*vec3(step(abs(A.z+.002),.002)*A.xy+.03*J.xy,1));"
               "bool I=H.x<0.;"
               "H=vec2(abs(abs(H.x)-.68),(H.y-.78)*sign(H.x));"
               "vec3 K=f(H,vec2(.15),.05);"
               "if(K.z<0.)"
                 "k=mat3((K.z>-.01||abs(H.x)<.16&&abs(H.x-H.y-.08)<.05)^^I?"
                   "vec3(.1,.1,.3):"
                   "vec3(.9),vec3(0),vec3(.5,0,20));"
             "}"
           "else if(k[2].z==4.)"
             "{"
               "vec2 H=F.xz;"
               "H-=floor(H/6.+.5)*6.;"
               "k=abs(H.x)<.7&&abs(H.y)<.2?"
                 "mat3(vec3(.3),F.z>-3.?"
                   "vec3(10):"
                   "vec3(0),vec3(.04,1,0)):"
                 "abs(H.x)<.72&&abs(H.y)<.22?"
                   "mat3(vec3(.8),vec3(0),vec3(.1,1,0)):"
                   "(H=F.xz,abs((floor(F.z/.2)+.5)*.2-F.z)<.09?"
                     "mat3(vec3(.8),vec3(0),vec3(.5,0,0)):"
                     "mat3(vec3(.02),vec3(0),vec3(.8,0,0)));"
             "}"
           "else if(k[2].z==7.)"
             "{"
               "vec2 H=k[0].xy/vec2(.012,.016);"
               "if(abs(H.y)>16.)"
                 "k=mat3(cos(.6*(H.x-H.y))>0.?"
                   "vec3(1,.5,0):"
                   "vec3(0),vec3(0),vec3(.1,0,0));"
               "else"
                 "{"
                   "float G=1.;"
                   "H.x+=27.;"
                   "f(H,G,0,7,0,5,0);"
                   "f(H,G,-6,5,6,5,0);"
                   "f(H,G,-4,3,-2,-5,-.1);"
                   "f(H,G,4,3,1,-7,-.3);"
                   "f(H,G,-7,-7,7,-7,0);"
                   "H.x-=18.;"
                   "f(H,G,-3,7,0,7,0);"
                   "f(H,G,0,7,-7,-7,-1.);"
                   "f(H,G,0,7,7,-7,1.);"
                   "H.x-=18.;"
                   "f(H,G,-7,6,-1,6,0);"
                   "f(H,G,-4,7,-4,2,0);"
                   "f(H,G,-4,6,-7,2.5,-.2);"
                   "f(H,G,-4,6,-1,2.5,.2);"
                   "f(H,G,1,6,7,6,0);"
                   "f(H,G,4,7,4,2,0);"
                   "f(H,G,4,6,1,2.5,-.2);"
                   "f(H,G,4,6,7,2.5,.2);"
                   "f(H,G,-6,0,6,0,0);"
                   "f(H,G,-7,-2.5,7,-2.5,0);"
                   "f(H,G,0,-2.5,0,-7,0);"
                   "f(H,G,0,-7,-2,-7,0);"
                   "f(H,G,-3,-4.5,-6.5,-7,-.5);"
                   "f(H,G,3,-4.5,6.5,-7,.3);"
                   "H.x-=18.;"
                   "f(H,G,0,7,0,-7,0);"
                   "f(H,G,0,2,6,2,0);"
                   "f(H,G,-4,3,-4,-7,0);"
                   "f(H,G,-7,-7,7,-7,0);"
                   "k[0]=G<1.?"
                     "vec3(.7,0,0):"
                     "vec3(1);"
                 "}"
               "k=mat3(mix(vec3(.04),vec3(.9),k[0]),vec3(0),vec3(.1,0,20));"
               "B.xyz=normalize(B.xyz);"
             "}"
           "else if(k[2].z==8.)"
             "{"
               "float G=step(.5,p(20.*F).x);"
               "k=mat3(mix(vec3(.5,.1,.02),vec3(.1,.02,.03),G),vec3(0),vec3(mix(.4,1.,G),0,20));"
               "B.xyz=normalize(B.xyz+.04*p(80.*F));"
             "}"
           "else if(k[2].z==9.)"
             "k=mat3(vec3(.3),vec3(0),vec3(.7,1,0));"
           "d=f(d);"
           "if(k[2].z!=5.)"
             "{"
               "float G=.2*smoothstep(0.,1.,p(F).x);"
               "k[2].x=mix(k[2].x,1.,G);"
               "if(smoothstep(0.,1.,.5*p(F).y-F.y-.2*F.z)>d.x)"
                 "k[0]=vec3(0),k[1]=vec3(0),k[2].x=.04;"
             "}"
           "if(k[2].z==20.)"
             "if(pow(.5+.5*p(20.*p(F.xyz)).x,8.)>d.x)"
               "k=mat3(vec3(.1,.06,.04),k[1],vec3(1,0,0));"
           "c=F+B.xyz*.001;"
           "float H=k[2].x*k[2].x,G=H*H;"
           "d=f(d);"
           "{"
             "float A=clamp(dot(B.xyz,-e),0.,1.),I=mix(.04,1.,pow(1.-A,5.)),J=max(step(d.x,I),k[2].y);"
             "v.xyz+=clamp(b,0.,4.)*(1.-I)*k[1];"
             "d.y=sqrt((1.-d.y)/(1.-J*(1.-G)*d.y));"
             "vec3 K=n(B.xyz)*vec3(sqrt(1.-d.y*d.y)*sin(x*d.z+vec2(0,x/4.)),d.y);"
             "if(J>0.)"
               "{"
                 "float L=clamp(dot(B.xyz,reflect(e,K)),0.,1.),M=clamp(dot(B.xyz,K),0.,1.),N=clamp(dot(-e,K),0.,1.),O=.5*H;"
                 "b*=L>0.&&M>0.?"
                   "mix(mix(vec3(.04),k[0],k[2].y),vec3(1),pow(1.-N,5.))/mix(I,1.,k[2].y)*L/(L*(1.-O)+O)/(A*(1.-O)+O)*N/M:"
                   "vec3(0);"
                 "K=reflect(e,K);"
               "}"
             "else"
               "{"
                 "if(dot(K,B.xyz)<0.)"
                   "break;"
                 "b*=(1.-mix(.04,1.,pow(1.-clamp(dot(-e,normalize(-e+K)),0.,1.),5.)))/(1.-I)*k[0];"
                 "if(k[2].z==6.)"
                   "{"
                     "c-=.002*B.xyz;"
                     "continue;"
                   "}"
               "}"
             "e=K;"
           "}"
           "if(dot(b,b)<.01)"
             "break;"
         "}"
     "}"
   "v.w=float(10);"
 "}";

#endif // FRAG_DRAW_H_
